[package]
name = "tuigreet"
version = "0.7.1"
authors = ["Antoine POPINEAU <antoine.popineau@appscho.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
chrono = { version = "^0.4.19", features = ["unstable-locales"] }
crossterm = { version = "0.21.0", features = ["event-stream"] }
futures = "0.3.17"
getopts = "^0.2.21"
greetd_ipc = { version = "0.8.0", features = ["tokio-codec"] }
i18n-embed = { version = "^0.13.0", features = ["desktop-requester", "fluent-system"] }
i18n-embed-fl = "^0.6.0"
lazy_static = "^1.4.0"
nix = "^0.23.0"
tui = { version = "^0.16.0", default-features = false, features = ["crossterm"] }
rust-embed = "^6.2"
rust-ini = "^0.17.0"
smart-default = "0.6.0"
textwrap = "^0.14.0"
tokio = { version = "1.2", default_features = false, features = ["macros", "rt-multi-thread", "net", "sync", "time", "process"] }
unic-langid = "^0.9"
zeroize = "^1.3.0"

[profile.release]
lto = true
